### ISSUE TITLE
Downloading ImageNet21k-OVR

### ISSUE THREAD

**Issue by leeuhh** [Zehong-Ma/OVMR#3]
Thank you for sharing your code. However, I noticed that the download link for `imagenet21k-OVR` (including `shot_64-seed_1.pkl`) is not provided in the repository. Would it be possible to share the link? It would be greatly appreciated.

**Comment by Zehong-Ma** [comment]
I have uploaded the dataset to the huggingface. Please manually download the files from https://huggingface.co/datasets/zehongma/ImageNet21k_OVR
