### ISSUE TITLE
ModuleNotFoundError: No module named 'dassl.data'

### ISSUE THREAD

**Issue by Au-LiuJY** [Zehong-Ma/OVMR#5]
Hi,I'm more than delighted to see your excellent work to open source.And I try to reproduce your work follow your guidance.
After I prepare the necessary environment setting,I meet some errors:
(ovmr) $ sh train.sh
Traceback (most recent call last):
  File "/OVMR/train.py", line 7, in <module>
    from dassl.engine import build_trainer
  File "/OVMR/Dassl.pytorch/dassl/engine/__init__.py", line 2, in <module>
    from .trainer import TrainerX, TrainerXU, TrainerBase, SimpleTrainer, SimpleNet  # isort:skip
  File "/OVMR/Dassl.pytorch/dassl/engine/trainer.py", line 11, in <module>
    from dassl.data import DataManager
ModuleNotFoundError: No module named 'dassl.data'

Hoping that you can answer me at your convenience.Thanks in advance!

**Comment by Zehong-Ma** [comment]
Apologies for the mistake during uploading. Due to the `data/` entry in `.gitignore`, the `data` folder in the `Dassl.pytorch` has not been uploaded as expected. I have corrected this issue and uploaded the `Dassl.pytorch/dassl/data`. Thank you for your attention and continued support of our work!

**Comment by Au-LiuJY** [comment]
> Apologies for the mistake during uploading. Due to the `data/` entry in `.gitignore`, the `data` folder in the `Dassl.pytorch` has not been uploaded as expected. I have corrected this issue and uploaded the `Dassl.pytorch/dassl/data`. Thank you for your attention and continued support of our work!

Haha！Thank you ~
